"""
End-to-end project run (Step 50).

Runs the whole deterministic project in one shot and writes a single
consolidated report to ``RESULTS.md`` at the repo root:

    * the four offline test suites          (pass/fail + output)
    * the 16-scenario evaluation benchmark  (full report)
    * a deterministic match per sample scenario
      (timeline + aggregated analytics, via the existing modules)

No AWS credentials, no Bedrock calls, no randomness - identical output on
every run. Exit code is non-zero if any suite or the benchmark fails.

    python -m scripts.run_full_demo [--ticks N] [--out PATH]
"""

from __future__ import annotations

import argparse
import io
import os
import subprocess
import sys
from contextlib import redirect_stdout
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.ai.match_simulator import HybridMatchSimulator, SimulationMode  # noqa: E402
from app.analytics import build_event_log, format_analytics, format_timeline  # noqa: E402
from app.core import sample_scenario  # noqa: E402

OFFLINE_SUITES = [
    "tests.test_core",
    "tests.test_agents",
    "tests.test_benchmark",
    "tests.test_analytics",
]

DEMO_SCENARIOS = [
    "create_shooting_scenario",
    "create_midfielder_pass_scenario",
    "create_defensive_scenario",
    "create_goalkeeper_emergency_scenario",
]


def _run_module(module: str) -> tuple[int, str]:
    """Run ``python -m <module>`` in a clean subprocess, capturing all output."""

    env = {**os.environ, "PYTHONIOENCODING": "utf-8"}
    proc = subprocess.run(
        [sys.executable, "-m", module],
        capture_output=True,
        text=True,
        env=env,
        cwd=str(ROOT),
    )
    return proc.returncode, (proc.stdout + proc.stderr).strip()


def _fence(text: str) -> str:
    return "```\n" + text.strip() + "\n```"


def _benchmark_report() -> str:
    from app.evaluation import format_report, run_benchmark

    buf = io.StringIO()
    with redirect_stdout(buf):
        report = run_benchmark()
    return format_report(report)


def _match_section(scenario_name: str, ticks: int) -> str:
    factory = getattr(sample_scenario, scenario_name)
    match = HybridMatchSimulator(
        factory(), mode=SimulationMode.DETERMINISTIC_ONLY, max_ticks=ticks
    ).run()
    log = build_event_log(match)

    return "\n".join(
        [
            f"### {scenario_name}  ({ticks} ticks, DETERMINISTIC_ONLY)",
            "",
            "**Timeline**",
            "",
            _fence(format_timeline(log)),
            "",
            "**Analytics**",
            "",
            _fence(format_analytics(log)),
            "",
        ]
    )


def build_report(ticks: int) -> tuple[str, bool]:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    lines: list[str] = [
        "# RESULTS — end-to-end project run",
        "",
        "> Generated by `python -m scripts.run_full_demo`. Deterministic and "
        "offline — re-running reproduces this file byte-for-byte "
        "(the `Generated` timestamp aside).",
        "",
        f"- Generated: {stamp}",
        f"- Python: {sys.version.split()[0]}",
        f"- Match ticks: {ticks}",
        "",
        "---",
        "",
        "## 1. Offline test suites",
        "",
    ]

    all_ok = True

    suite_rows = []
    suite_outputs = []
    for suite in OFFLINE_SUITES:
        code, output = _run_module(suite)
        ok = code == 0
        all_ok = all_ok and ok
        suite_rows.append(f"| `{suite}` | {'PASS' if ok else 'FAIL'} | {code} |")
        suite_outputs.append((suite, ok, output))

    lines += ["| Suite | Result | Exit code |", "|---|---|---|", *suite_rows, ""]
    for suite, ok, output in suite_outputs:
        tail = "\n".join(output.splitlines()[-12:])
        lines += [
            f"<details><summary>{suite} — {'PASS' if ok else 'FAIL'}</summary>",
            "",
            _fence(tail or "(no output)"),
            "",
            "</details>",
            "",
        ]

    lines += ["---", "", "## 2. Evaluation benchmark", "", _fence(_benchmark_report()), ""]

    lines += ["---", "", "## 3. Deterministic match runs", ""]
    for scenario_name in DEMO_SCENARIOS:
        lines.append(_match_section(scenario_name, ticks))

    lines += [
        "---",
        "",
        "## Summary",
        "",
        f"- Offline test suites: {'all PASS' if all_ok else 'FAILURES — see section 1'}",
        "- Evaluation benchmark: see section 2 (expected 16/16, 100.0%)",
        f"- Matches simulated: {len(DEMO_SCENARIOS)} scenarios × {ticks} ticks, "
        "deterministic-only (no Bedrock calls)",
        "",
        f"**Overall: {'PASS' if all_ok else 'FAIL'}**",
        "",
    ]

    return "\n".join(lines), all_ok


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ticks", type=int, default=8)
    parser.add_argument("--out", type=Path, default=ROOT / "RESULTS.md")
    args = parser.parse_args(argv)

    report, ok = build_report(args.ticks)
    args.out.write_text(report, encoding="utf-8")

    print(f"Wrote {args.out.relative_to(ROOT) if args.out.is_relative_to(ROOT) else args.out}")
    print(f"Overall: {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
